# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XkbConfig.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 540)
        MainWindow.setMaximumSize(QtCore.QSize(500, 540))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/xkbswitcher/AppIcon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.langView = QtGui.QListView(self.groupBox)
        self.langView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.langView.setAlternatingRowColors(True)
        self.langView.setObjectName(_fromUtf8("langView"))
        self.verticalLayout_3.addWidget(self.langView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.flagLabel = QtGui.QLabel(self.groupBox)
        self.flagLabel.setMaximumSize(QtCore.QSize(58, 55))
        self.flagLabel.setText(_fromUtf8(""))
        self.flagLabel.setScaledContents(False)
        self.flagLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.flagLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.flagLabel.setObjectName(_fromUtf8("flagLabel"))
        self.verticalLayout.addWidget(self.flagLabel)
        spacerItem = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.addButton = QtGui.QPushButton(self.groupBox)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.verticalLayout.addWidget(self.addButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.flagView = QtGui.QListView(self.groupBox)
        self.flagView.setMinimumSize(QtCore.QSize(48, 0))
        self.flagView.setMaximumSize(QtCore.QSize(150, 16777215))
        self.flagView.setViewMode(QtGui.QListView.IconMode)
        self.flagView.setObjectName(_fromUtf8("flagView"))
        self.verticalLayout_2.addWidget(self.flagView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.customFlagLabel = QtGui.QLabel(self.groupBox)
        self.customFlagLabel.setIndent(2)
        self.customFlagLabel.setObjectName(_fromUtf8("customFlagLabel"))
        self.horizontalLayout.addWidget(self.customFlagLabel)
        self.browseButton = QtGui.QPushButton(self.groupBox)
        self.browseButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.browseButton.setObjectName(_fromUtf8("browseButton"))
        self.horizontalLayout.addWidget(self.browseButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.resView = QtGui.QListWidget(self.groupBox_2)
        self.resView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.resView.setAlternatingRowColors(True)
        self.resView.setModelColumn(0)
        self.resView.setUniformItemSizes(True)
        self.resView.setObjectName(_fromUtf8("resView"))
        self.verticalLayout_4.addWidget(self.resView)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.moveUpButton = QtGui.QPushButton(self.groupBox_2)
        self.moveUpButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.moveUpButton.setObjectName(_fromUtf8("moveUpButton"))
        self.verticalLayout_5.addWidget(self.moveUpButton)
        self.removeButton = QtGui.QPushButton(self.groupBox_2)
        self.removeButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.verticalLayout_5.addWidget(self.removeButton)
        self.moveDownButton = QtGui.QPushButton(self.groupBox_2)
        self.moveDownButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.moveDownButton.setObjectName(_fromUtf8("moveDownButton"))
        self.verticalLayout_5.addWidget(self.moveDownButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "XkbSwitch Configuration", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Type a few letters (Country or Language)", None))
        self.addButton.setText(_translate("MainWindow", "Add", None))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Filter by Country Code", None))
        self.customFlagLabel.setText(_translate("MainWindow", "Set custom icon", None))
        self.browseButton.setText(_translate("MainWindow", "Browse Files", None))
        self.label.setText(_translate("MainWindow", "Added Languages", None))
        self.moveUpButton.setText(_translate("MainWindow", "Move Up", None))
        self.removeButton.setText(_translate("MainWindow", "Remove", None))
        self.moveDownButton.setText(_translate("MainWindow", "Move Down", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))

import XkbConfig_rc
